name: crud_excel
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  excel: ^4.0.6
  path: ^1.8.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
